---

# Secret for Delegate Token
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-delegate-account-token
  namespace: automation-snowflake-harness-1ad4c3
type: Opaque
data:
  DELEGATE_TOKEN: "MDY4OThiY2ZhZWI1YTA2MmIwZmE3OTRhMTM3MTIzYzM="

---

# Deployment using the existing 'pipeline' service account
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    harness.io/name: kubernetes-delegate
  name: kubernetes-delegate
  namespace: automation-snowflake-harness-1ad4c3
spec:
  replicas: 1
  minReadySeconds: 120
  selector:
    matchLabels:
      harness.io/name: kubernetes-delegate
  template:
    metadata:
      labels:
        harness.io/name: kubernetes-delegate
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3460"
        prometheus.io/path: "/api/metrics"
    spec:
      serviceAccountName: pipeline
      imagePullSecrets:
        - name: dockerhub-secret
      terminationGracePeriodSeconds: 3600
      restartPolicy: Always
      containers:
        # Delegate Container
        - image: sebastienlee93/delegate-with-liquibase-python:latest  # <-- Use your custom image here
          imagePullPolicy: Always
          name: delegate
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2048Mi"
            requests:
              cpu: "0.5"
              memory: "2048Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3460
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/health
              port: 3460
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 15
          envFrom:
            - secretRef:
                name: kubernetes-delegate-account-token
          env:
            - name: JAVA_OPTS
              value: "-Xms64M"
            - name: ACCOUNT_ID
              value: 1WYRE27PSGmNFgriapvh4Q
            - name: MANAGER_HOST_AND_PORT
              value: https://app.harness.io
            - name: DEPLOY_MODE
              value: KUBERNETES
            - name: DELEGATE_NAME
              value: kubernetes-delegate
            - name: DELEGATE_TYPE
              value: "KUBERNETES"
            - name: DELEGATE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INIT_SCRIPT
              value: ""
            - name: DELEGATE_DESCRIPTION
              value: ""
            - name: DELEGATE_TAGS
              value: ""
            - name: NEXT_GEN
              value: "true"
            - name: CLIENT_TOOLS_DOWNLOAD_DISABLED
              value: "true"
            - name: LOG_STREAMING_SERVICE_URL
              value: "https://app.harness.io/log-service/"
            - name: DELEGATE_RESOURCE_THRESHOLD
              value: ""
            - name: DYNAMIC_REQUEST_HANDLING
              value: "false"
---

# Horizontal Pod Autoscaler (optional)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-delegate-hpa
  namespace: automation-snowflake-harness-1ad4c3
  labels:
    harness.io/name: kubernetes-delegate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetes-delegate
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
