name: Deploy to GitHub Pages

on:
  # Trigger the workflow on push to main branch
  push:
    branches: [ main ]
  # Allow manual triggers from Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      # Move contents of dist to docs
      - name: Move build to docs
        run: |
          rm -rf docs/*
          mv docs/dist/* docs/
          rm -rf docs/dist
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
